version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Asumiendo que tienes un archivo de configuración de Nginx
    ports:
      - "80:80"
    depends_on:
      - node_app

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    expose:
      - "3000"  # Este puerto solo es visible dentro de la red de Docker
